#!/usr/bin/env python3
from params_proto import ParamsProto
from params_proto import Proto


class Args(ParamsProto):

    ## sdf options ##
    sdf_model_dir = Proto('/models/sdf', env='SDF_MODEL_DIR')
    sdf_model_name = 'simple_surface-normalized_step00056000.pt'  # 'simple.pt'  # tlfe.pt
    sdf_simple_arch = True
    sdf_points = 'surface_signed' # '_uniform' ''
    sdf_batch_size = 1000 # number of points we feed in to F_theta for each iteration

